version: '3.9'

services:
  qbittorrent-remover:
    build:
      context: .
    container_name: qbittorrent-remover
    environment:
      QB_URL: ${QB_URL}
      QB_USER: ${QB_USER}
      QB_PASS: ${QB_PASS}
    restart: unless-stopped